"""p-bit cell golden model — the frozen fixed-point contract (D13/D15).

Formats (FROZEN at M4; every later phase inherits them):
  J, h (couplings/bias): s1.6.3  — sign + 6 int + 3 frac = 10 bits, units 1/8
  accumulator:           s1.10.3 — 14 bits, units 1/8 (8 neighbors + bias
                          cannot overflow: 9 * 63.875 = 574.9 < 1023.875)
  beta (inverse temp):   u2.6    — 8 bits, units 1/64, range [0, 3.984]
  z = acc*beta:          product units 2^-9; SIGN-MAGNITUDE round-half-away
                          (mag = (|prod|+1)>>1) to u4.8 + sign, saturated to
                          |z| <= 12 - 2^-8 — symmetric by construction, so
                          p17(a) + p17(-a) == 65536 exactly for every input
  sigmoid LUT:           entries round(sigma(i/256)*65536) clamped to 65535,
                          for i in [0, 3072) covering z in [0,12); negative z
                          by symmetry p17 = 65536 - LUT[-z]
  decision:              s = 1  iff  rnd[31:16] < p17   (P = p17/65536 exact)

Spin modes: binary s in {0,1} (contribution s?J:0) or bipolar (s?+J:-J).

The RTL (rtl/pbit/pbit_cell.sv) is bit-true to p17()/decision(); the bench
diffs them EXACTLY per update. The LUT-accuracy spec (M4 gate, frozen):
max |p17/65536 - sigma_ideal(acc/8 * beta/64)| <= 7.0e-4 over the full
reachable (acc, beta) grid — dominated by the 2^-9 z-quantization step.
"""
from __future__ import annotations

import numpy as np

LUT_N = 3072          # [0, 12) step 1/256
ACC_MIN, ACC_MAX = -(1 << 13), (1 << 13) - 1     # s14 raw (units 1/8)
ERR_BOUND = 7.0e-4    # frozen LUT accuracy spec vs ideal sigmoid


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.asarray(z, dtype=np.float64)))


def lut_table() -> np.ndarray:
    z = np.arange(LUT_N, dtype=np.float64) / 256.0
    return np.minimum(np.rint(sigmoid(z) * 65536.0), 65535.0).astype(np.uint32)


_LUT = lut_table()


def q_s163(x: float) -> int:
    """Quantize a float to s1.6.3 raw units (1/8), saturating."""
    r = int(round(x * 8.0))
    return max(-511, min(511, r))


def q_beta(x: float) -> int:
    return max(0, min(255, int(round(x * 64.0))))


def mac(bias_raw: int, neighbors: list[tuple[int, int]], bipolar: bool) -> int:
    """neighbors: (j_raw, s in {0,1}). Returns acc raw (s14 range asserted)."""
    acc = bias_raw
    for j, s in neighbors:
        if bipolar:
            acc += j if s else -j
        else:
            acc += j if s else 0
    assert ACC_MIN <= acc <= ACC_MAX, "MAC overflow — degree contract broken"
    return acc


def p17(acc_raw: int, beta_raw: int) -> int:
    """Bit-true probability numerator (P(s=1) = p17/65536)."""
    prod = acc_raw * beta_raw           # units 2^-9, fits s22
    neg = prod < 0
    mag = ((-prod if neg else prod) + 1) >> 1    # units 2^-8, half-away
    if mag > LUT_N - 1:
        mag = LUT_N - 1                 # saturate to 12 - 2^-8
    pl = int(_LUT[mag])
    return (65536 - pl) if neg else pl


def decision(acc_raw: int, beta_raw: int, rnd32: int) -> tuple[int, int]:
    p = p17(acc_raw, beta_raw)
    return int((rnd32 >> 16) < p), p


def write_lut_mem(path: str) -> None:
    with open(path, "w") as f:
        f.write("// generated by golden/pbit.py — sigma LUT, u0.16, [0,12) step 1/256\n")
        for v in _LUT:
            f.write(f"{v:04x}\n")


def lut_accuracy_report() -> dict:
    """Max |bit-true p - ideal sigmoid| over the full reachable grid."""
    acc = np.arange(ACC_MIN, ACC_MAX + 1, dtype=np.int64)
    worst = 0.0
    worst_at = (0, 0)
    for b in range(1, 256):             # beta=0 -> p=0.5 exactly, trivially ideal
        prod = acc * b
        neg = prod < 0
        mag = (np.abs(prod) + 1) >> 1
        mag = np.minimum(mag, LUT_N - 1)
        pl = _LUT[mag].astype(np.int64)
        p = np.where(neg, 65536 - pl, pl).astype(np.float64) / 65536.0
        ideal = sigmoid(acc / 8.0 * (b / 64.0))
        err = np.abs(p - ideal)
        i = int(err.argmax())
        if err[i] > worst:
            worst = float(err[i])
            worst_at = (int(acc[i]), b)
    return {"max_err": worst, "at_acc_beta": worst_at, "bound": ERR_BOUND,
            "ok": worst <= ERR_BOUND}


if __name__ == "__main__":
    assert p17(0, 128) == 32768                      # sigma(0) = 1/2 exactly
    assert decision(0, 128, 0x7FFF_0000)[0] == 1     # 0x7fff < 32768
    assert decision(0, 128, 0x8000_0000)[0] == 0     # 0x8000 !< 32768
    for a, b in [(40, 64), (-40, 64), (511, 255), (-511, 255), (3, 7)]:
        assert p17(a, b) + p17(-a, b) == 65536, (a, b)   # exact symmetry
    m = mac(q_s163(1.5), [(q_s163(-2.0), 1), (q_s163(0.5), 0)], bipolar=True)
    assert m == q_s163(1.5) - q_s163(2.0) - q_s163(0.5)
    r = lut_accuracy_report()
    assert r["ok"], r
    print(f"pbit golden self-check OK — LUT max err {r['max_err']:.2e} "
          f"(bound {ERR_BOUND:.1e}) at acc,beta={r['at_acc_beta']}")
